modLoader = "javafml"
loaderVersion = "[38,)"
license = "LGPLv3"

[[mods]]
modId = "forgematica"
version = "${version}"
displayName = "Re-Forgematica"
displayURL="https://github.com/HoYin1600p/Re-Forgematica" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="HoYin1600p, TexTrue, ThinkingStudio" #optional
description = '''
Re-Forgematica fork of the unofficial Litematica Forge port.

Adds survival-focused Forge 1.18.2 schematic workflow improvements.
'''

[[dependencies.forgematica]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgematica]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgematica]]
modId = "mafglib"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
